### ISSUE TITLE
Remove redundant message on landing page

### ISSUE THREAD

**Issue by kljensen** [kljensen/yale-class-chat#104]
<img width="840" alt="Screen Shot 2020-04-01 at 3 56 56 PM" src="https://user-images.githubusercontent.com/73154/78180962-8ca40380-7431-11ea-88d2-1d27989ce26a.png">

**Comment by nperanzi** [comment]
Message is no longer present as of 05869f96709a40750095ffdddc7ac1eb676b8f83
