### ISSUE TITLE
avoid writing to the filesystem

### ISSUE THREAD

**Issue by kljensen** [kljensen/yale-class-chat#109]
https://github.com/kljensen/yale-class-chat/blob/510f78a553ecbf2190073c9e928e535039ff812b/app/lib/app/submissions.ex#L1374

generally this is not a good practice. we ought to be able to write to some file-like thing that is in memory. in python this would be like `stringio`, but i'm not sure what it is in elixir

**Comment by kljensen** [comment]
we could also just get back raw CSV from postgres. dunno how we do that with ecto, but might make it possible to stream response directly to the http client

**Comment by nperanzi** [comment]
Resolved in 05869f96709a40750095ffdddc7ac1eb676b8f83, now streams directly to http client
