### ISSUE TITLE
Hide course/topic edit from students

### ISSUE THREAD

**Issue by kljensen** [kljensen/yale-class-chat#20]
I believe right now students are able to navigate to URLs like http://localhost:9001/sections/1/edit for the purpose of editing. Submitting the form returns the following error (screenshot)

`
no case clause matching: {:error, "unauthorized"}
`

for an unconvered branch in a match block. 

<img width="1392" alt="Screen Shot 2020-03-11 at 7 39 56 PM" src="https://user-images.githubusercontent.com/73154/76482064-5e9e4700-63d0-11ea-80cf-2bbd00138a8c.png">

**Comment by nperanzi** [comment]
Correct (btw, those errors will appear as 404 or 500 in prod environments). Will implement a fix!

**Comment by nperanzi** [comment]
Fix implemented for courses, sections, topics, and submissions. Will implement for comments and ratings as well!

**Comment by nperanzi** [comment]
Fixed for comments and ratings as of 2370de793de738dd079ec7e75899b5a5debd2e1b
