### ISSUE TITLE
Latest dev has timeouts on db init

### ISSUE THREAD

**Issue by kljensen** [kljensen/yale-class-chat#26]
Working off of 12cf981ee949d94d330ab4811050294c53660ec2, I was unable to start the app using `./admin.sh up` due to some kind of timeout with database initialization. I'm unsure of the cause. I am able to start the app from the latest `front-end` branch. 

Exception looks like the following:

```
app_1      | The mix.lock file was generated with a newer version of Hex. Update your client by running `mix local.hex` to avoid losing data.
tests_1    | The mix.lock file was generated with a newer version of Hex. Update your client by running `mix local.hex` to avoid losing data.
tests_1    | ** (Mix) The database for App.Repo couldn't be created: connection not available and request was dropped from queue after 2965ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
tests_1    |
tests_1    |   1. By tracking down slow queries and making sure they are unning fast enough
tests_1    |   2. Increasing the pool_size (albeit it increases resource consumption)
tests_1    |   3. Allow requests to wait longer by increasing :queue_target and :queue_interval
tests_1    |
tests_1    | See DBConnection.start_link/2 for more information
```

**Comment by kljensen** [comment]
Closing, this was an issue with my docker.

**Comment by kljensen** [comment]
Reopening because I continue to have this issue ...not sure if it is me (hard to see how it could be my docker setup in particular....but is possible)

**Comment by kljensen** [comment]
FYI - I am not seeing this on my linux machine. Not sure WTF. Will keep it open for a bit

**Comment by nperanzi** [comment]
Are you still encountering this issue on non-linux machines? I exclusively develop on Linux (Docker on Windows has loads of permissions issues so I am unable to use live-reload and am consistently forced to reboot just to edit a file I just created, and I don't own a Mac anymore).
