### ISSUE TITLE
UndefinedFunctionError for comment detail

### ISSUE THREAD

**Issue by kljensen** [kljensen/yale-class-chat#27]
Seeing this exception

```
UndefinedFunctionError at GET /comments/7
function App.Submission.Comment.__schema__/1 is undefined (module App.Submission.Comment is not available)
```

when visiting `/comments/7` as `stud2`

Also, stud2 is a hilarious username.

**Comment by nperanzi** [comment]
Oops! Typo in module name. Fixed in 1c787d57d8916f7ffc1252a5858a2119df606884
