### ISSUE TITLE
Rating averages different between list and detail views

### ISSUE THREAD

**Issue by kljensen** [kljensen/yale-class-chat#53]
See `/topics/1` (rate my teaching ability) says 5 ratings avg = 3. But, clicking on its detail view `/submissions/2` shows instead 1 rating average= 2.

**Comment by nperanzi** [comment]
I am only able to duplicate this if I click the back button to see `/topics/1` (which shows old data) after submitting a rating. Will keep trying to duplicate the issue.

**Comment by nperanzi** [comment]
Closing as discussed via email - please reopen if you see this again.
