### ISSUE TITLE
Move "delete" option for class to class admin (for prof)

### ISSUE THREAD

**Issue by kljensen** [kljensen/yale-class-chat#73]
That "delete" option is going to give people a lot of worry. Likely we should move it to the admin page and then also hide it under some kind of expanding div or require text confirmation like Github does when deleting a repo. also, can only owner delete?

**Comment by nperanzi** [comment]
Moved in 81374a30879d329173f731ce9e5c51fbf62504a0; also hidden from administrators (only owners can edit or delete courses, add/edit/delete sections, and add/edit/delete course roles). Will create a new issues to add info on what the roles do.
