### ISSUE TITLE
I can't post

### ISSUE THREAD

**Issue by regemeno** [kljensen/yale-class-chat#76]
When I am trying to post an idea, it is not working.

**Comment by kljensen** [comment]
Thanks what section are you in ?

**Comment by regemeno** [comment]
I am in the Gold Cohort.

Best,
Rüya

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nperanzi** [comment]
Hi Rüya - what is your net id? Do you see any messages or other indications that your post isn't working? If so, could you attach a screenshot?

I'm not seeing any obvious misconfiguration issues, so the above questions will help me to get this fixed for you as quickly as possible.

-Nick

**Comment by nperanzi** [comment]
Also, can you confirm that you're trying to submit from this link: https://yale.chat/topics/10 ?

**Comment by nperanzi** [comment]
Looks like you are now able to post (https://yale.chat/submissions/8); closing this issue. Please let us know if you experience more issues!
