### ISSUE TITLE
Maybe clean up landing page?

### ISSUE THREAD

**Issue by kljensen** [kljensen/yale-class-chat#89]
Nick - did you want all this stuff on the landing page?  Seems like a bit bunch. I suggest we drop the exaltation, keep the caveats, and make a big fat login button.

**Comment by nperanzi** [comment]
Gah, perils of placeholder text. Fixing now!

**Comment by nperanzi** [comment]
Fixed in afe518f8999622d180e3eef6ec95e51818c0e4f9

Removed exaltation, moved experimental bit to the description, and also dropped our names from the first card (as they now appear in the footer). Increased size of button and made it point to login rather than about
