### ISSUE TITLE
Refactor client-facing error handling

### ISSUE THREAD

**Issue by kljensen** [kljensen/yale-class-chat#90]
Code like this https://github.com/kljensen/yale-class-chat/blob/master/app/lib/app_web/controllers/topic_controller.ex#L21 is duplicated in many places

```elixir
      {:error, message} ->
        case message do
          "forbidden" ->
            conn
            |> put_status(:forbidden)
            |> put_view(AppWeb.ErrorView)
            |> render("403.html")
          "not found" ->
            conn
            |> put_status(:not_found)
            |> put_view(AppWeb.ErrorView)
            |> render("404.html")
          end
```

Better to refactor that into a function like

```elixir
      {:error, message} -> render_error :error, message
```

**Comment by nperanzi** [comment]
This specific issue with controllers has been resolved as of 42c3b65bd94dde52bcde557f05827b3ceb110eb8; closing this issue but leaving #91 open as a larger cleanup is still necessary.
