### ISSUE TITLE
Integrate LDAP connection to pull user display name, email, and faculty status

### ISSUE THREAD

**Issue by nperanzi** [kljensen/yale-class-chat#95]

**Comment by kljensen** [comment]
I don’t think faculty status is a categorical variable but rather must be
parsed from string. I could be wrong. All faculty will be some kind of
“lecturer” or “Professor”.

**Comment by nperanzi** [comment]
Implemented in cdad5d2e62143a8f957997e5748d3baedc6c764e

For faculty, we check if the user is a member of the All_Faculty group (CN=All_Faculty,OU=General Access,OU=Applications,OU=Enterprise Systems,OU=Information Technology Services,DC=yu,DC=yale,DC=edu)
