### ISSUE TITLE
Pin footer to the bottom

### ISSUE THREAD

**Issue by kljensen** [kljensen/yale-class-chat#98]
Likely we'd prefer something as described here [https://www.freecodecamp.org/news/how-to-keep-your-footer-where-it-belongs-59c6aa05c59c/](https://www.freecodecamp.org/news/how-to-keep-your-footer-where-it-belongs-59c6aa05c59c/) to our current footer, which can be oddly placed when the content is short relative to viewport height.

![Screen Shot 2020-03-26 at 7 32 39 AM](https://user-images.githubusercontent.com/73154/77642457-133d7a00-6f34-11ea-84a4-318240bab1f2.png)

**Comment by nperanzi** [comment]
Implemented in a31fe29f74a5d55dd455bf4492a9e5ec1f59accb
